import Vue from 'vue'
import { Button, Icon, Header, Container, Aside, Main, Footer, Menu, Submenu, MenuItemGroup, Avatar, Row, Col, Input, Popover, MenuItem, Message, Link, Dialog, Card, Form, FormItem, Carousel, CarouselItem, Image, Tabs, TabPane, Table, TableColumn, Backtop, Pagination, Progress, Upload } from 'element-ui'

Vue.use(Button)
Vue.use(Upload)
Vue.use(Progress)
Vue.use(Pagination)
Vue.use(Icon)
Vue.use(Backtop)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Header)
Vue.use(Container)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Row)
Vue.use(Col)
Vue.use(Input)
Vue.use(Popover)
Vue.use(Link)
Vue.use(Avatar)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(MenuItem)
Vue.use(Dialog)
Vue.use(Card)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Image)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.prototype.$message = Message
